Ex 02
anderhos/INF200-2019-Exercises pull request #3
Opened 2019-09-27 11:46 UTC by anderhos

Tried my best

2019-10-01 15:35 UTC, ahmedalbuni commented on src/Anders_Hoest_ex02/bubble_sort.py
> +            if dataset[j] > dataset[j+1]:
you should modify the newly created list here, not the original list, you are getting a runtime exception here also because of the type of returned list

2019-10-01 15:37 UTC, ahmedalbuni commented on src/Anders_Hoest_ex02/message_entropy.py
> +from collections import Counter, defaultdict
unused import here

2019-10-01 15:38 UTC, ahmedalbuni requested changes
File bubble sort does not work due to the returned value type, and one pep8 violation (unused import)

2019-10-02 09:41 UTC, anderhos commented on src/Anders_Hoest_ex02/message_entropy.py
> +from collections import Counter, defaultdict
Ok. Removed defaultdict.

2019-10-02 09:44 UTC, anderhos commented on src/Anders_Hoest_ex02/bubble_sort.py
> +            if dataset[j] > dataset[j+1]:
Edited so that the code modifies list_dataset instead of the orginal list (dataset).

2019-10-02 09:44 UTC, merged